name = "FlexiJoins"
uuid = "e37f2e79-19fa-4eb7-8510-b63b51fe0a37"
authors = ["Alexander Plavin <alexander@plav.in>"]
version = "0.1.33"

[deps]
Accessors = "7d9f7c33-5ae7-4f3b-8dc6-eff91059b697"
ArraysOfArrays = "65a8f2f4-9b39-5baf-92e2-a9cc46fdf018"
DataAPI = "9a962f9c-6df0-11e9-0e5d-c546b8b5ee8a"
DataPipes = "02685ad9-2d12-40c3-9f73-c6aeda6a7ff5"
FlexiMaps = "6394faf6-06db-4fa8-b750-35ccc60383f7"
IntervalSets = "8197267c-284f-5f27-9208-e0e47529a953"
NearestNeighbors = "b8a86587-4115-5ab1-83bc-aa920d37bbce"
SentinelViews = "1c95a9c1-8e3f-460f-8963-106dcc440218"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"

[weakdeps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
SkyCoords = "fc659fc5-75a3-5475-a2ea-3da92c065361"

[extensions]
DataFramesExt = "DataFrames"
SkyCoordsExt = "SkyCoords"

[compat]
Accessors = "0.1.9"
ArraysOfArrays = "0.5.8, 0.6"
DataAPI = "1.9.0"
DataFrames = "1"
DataPipes = "0.2.10, 0.3"
FlexiMaps = "0.1"
IntervalSets = "0.7.1 - 0.7.7"
NearestNeighbors = "0.4.10"
SentinelViews = "0.1.3"
SkyCoords = "1.3.0"
StaticArrays = "1.5.1"
StructArrays = "0.6.5"
julia = "1.9"
